name: GitHub Actions Demo
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  GraphQL-Keep-Awke:
    runs-on: curlimages/curl
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
      - run: echo "Hitting the graphql endpoint"
      - run: curl -X POST https://www.prescottjr.com/api/graphql
