import React from 'react';
import Head from 'next/head';
import styled, { keyframes } from 'styled-components';

const Container = styled.div`
  border: 10px solid;
  border-image: url('/rainbow-bar.png') 30 round;
  align-items: center;
  justify-content: center;
  display: flex;
  width: 100vw;
  height: 100vh;
  overflow-y: hidden;
`;

const SlowRotation = keyframes`
  50% {
    transform: scale3d(1.05, 1.05, 1.05);
  }
  //50% {
  //  transform: rotate(180deg);
  //}
  //100% {
  //  transform: rotate(360deg);
  //}

`;

const Title = styled.h1`
  font-size: 128px;
  font-family: Shrimp;
`;

const ImageBackground = styled.div`
  animation: ${SlowRotation};
  animation-timing-function: ease-in-out;
  animation-duration: 10s;
  animation-iteration-count: infinite;
  position: absolute;
  background-image: url('/splatter.png');
  background-size: 100vw;
  width: 100%;
  height: 100%;
  z-index: -1;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Prescott&apos;s Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageBackground />
      <Title>PRESCOTT</Title>
      <Title>J</Title>
      <Title>RYNEWICZ</Title>
    </Container>
  );
}
